import { defineNuxtPlugin } from 'nuxt/app'

/**
 * Registers the workbox service worker generated by @vite-pwa/nuxt (served at
 * /sw.js in the production build) so the dashboard is installable. Skipped in
 * dev, where no sw.js is emitted. registerType 'autoUpdate' means the SW
 * activates new versions on its own.
 */
export default defineNuxtPlugin(() => {
  if (import.meta.dev) return
  if (!import.meta.client || !('serviceWorker' in navigator)) return
  const register = () => navigator.serviceWorker.register('/sw.js').catch(() => {})
  // Hydration can run after `load` has already fired, so register right away in
  // that case instead of waiting for an event that won't come.
  if (document.readyState === 'complete') register()
  else window.addEventListener('load', register, { once: true })
})
